services:
  flask:
    restart: unless-stopped
    build:
      context: ./app
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          cpus: "1.0"
          memory: 512M
    ports:
      - mode: ingress
        target: 5001
        published: 5001
    