services:
  flask-new:
    restart: unless-stopped
    build:
      context: ./app
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          cpus: "1.0"
          memory: 512M
    ports:
      - mode: ingress
        target: 5001
        published: 5001
  lazy-scheduler:
    restart: unless-stopped
    env_file: "./fe/.env"
    # domainname: mydomain.com # if you want to use your own domain
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - target: 3000
        mode: ingress
        published: 3000
    deploy:
      resources:
        reservations:
          cpus: '0.50'
          memory: 512M
    